### ISSUE TITLE
crash after starting campaign

### ISSUE THREAD

**Issue by milesvor** [sd805/l4d2vr#2]
Valve index + knuckles, gtx1080 + ryzen 3600, 32GB ram, SteamVr beta, windows 10 pro updated.
Used the parameters as in readme (additional parameters for exe, video settings)
After finishing loading a campaign, the HMD turn black and immediately after the game crash
In the debug log there is this line
[0510/224430:INFO:dhcp_proxy_script_adapter_fetcher_win.cc(265)] Error fetching PAC URL from DHCP: 2

Removing d3d9.dll the game does not crash but obviously VR is not working

**Comment by Richleth** [comment]
Mine was fixed by swapping to low paged pool memory but then the game won't launch into VR mode

**Comment by sd805** [comment]
Try disabling all add-ons and then verifying integrity of game files. Otherwise try setting paged pool memory to high and shaders/effects/textures to low.
Does it crash before activating VR mode?

**Comment by milesvor** [comment]
It seems it crashes while activating VR. These evening ill try your
suggestions and report.
Btw the game was installed from zero, also done validati cache files.

Il Mer 11 Mag 2022, 08:00 sd805 ***@***.***> ha scritto:

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
Having the same issue

**Comment by Hochgeschwindigkeitsrennfahrer** [comment]
> Try disabling all add-ons and then verifying integrity of game files. Otherwise try setting paged pool memory to high and shaders/effects/textures to low. Does it crash before activating VR mode?

That worked

**Comment by milesvor** [comment]
> 

Setting everithing on medium worked! Thanks, wonderful mod!!
