### ISSUE TITLE
Last 3 versions of L4D2vr - F6 and A on controller do nothing.

### ISSUE THREAD

**Issue by Hicks613** [sd805/l4d2vr#24]
Been watching these threads, desperate to play L4D2 in VR and nothing works.
As I've said elsewhere in this and other locations, VR does not kick in.
In Airlink and Link: I go to my windows desktop, open steam and launch the game (with the launch options included).
SteamVR launches and my steamvr wallpaper shows with "waiting..." showing.  Meanwhile on my pc screen, the game launches, I navigate to new single player and start up a local game.  I'm shown the intro and take control of my avatar...nothing.  I've been hammering that F6 button.  Fuckall happens.  A on controller does nothinhg.  The controllers do not make anything happen on screen.

I've tried varied approaches in Virtual Desktop as well.  Nothing works.  Somebody please respond to any one of my many posts.

**Comment by sd805** [comment]
This version will write a vr_log.txt file to your L4D2 directory. Run SteamVR and L4D2, load into a campaign, try pushing A/F6, quit the game, then copy and paste what's in vr_log.txt. 
[L4D2VR.zip](https://github.com/sd805/l4d2vr/files/8792459/L4D2VR.zip)

**Comment by zxv2007** [comment]
vr_log.txt

2022-05-29 10:56:19	Initializing L4D2VR
2022-05-29 10:56:19	Retrieving modules...
2022-05-29 10:56:21	Retrieved modules
2022-05-29 10:56:21	Initializing VR
2022-05-29 10:56:23	OpenVR initialized
2022-05-29 10:56:23	Compositor initialization failed.
2022-05-29 10:56:23	Initializing hooks
2022-05-29 10:56:23	Initializing DirectX hooks
2022-05-29 10:56:23	Initializing Source hooks

**Comment by Hicks613** [comment]
I did not have this file.  But i figured the OS must be blocking access to the mod.
So....

Windows DEFENDER FOLDER EXCLUSIONS were added.

F6 now works!  As does pressing "A".

I now have fixed arms in the ground.  No motion controls.  But I can move around.  THumbsticks work, all buttons work.  I can shoot.  I can pick up items, but my avatar arms are in the ground, therefore always shooting up dust.  I can even run away from my avatar arms and keep shotting the ground back there at the start point.

I, of course, get hammered by zombies.

Thanks for the tips.
I still don't have a VR_Log.txt though, but I have only tested with airlink.
I'll test VD when I get home in 30 mins.

**Comment by sd805** [comment]
@zxv2007 Are you using a beta version of SteamVR?

**Comment by Hicks613** [comment]
Further progress made:  I closed out of the Riva Statistics server.  This POS comes with EVGA Precision X as well as MSI Afterburner.
I use these for undervolting my 3080.
Once I closed it down and the related services. I had some luck just launching the game via virtual desktop, then steam vr, then launching from my steam 2d library or launching within the steam vr interface (where it says launch in theater mode)

The game launches constantly now without any issues.  Some grainy graphics I can't seem to fix even with steamvr scaling.
I also which I could do away with the fixed arms and their animations, but it is early days.

Many Thanks @sd805

**Comment by sd805** [comment]
Good to hear. There's also an invisible arms mod in the workshop if you prefer that: https://steamcommunity.com/sharedfiles/filedetails/?id=313902834

**Comment by Hicks613** [comment]
Subbed.  Thank you!

**Comment by SwiftShadow0** [comment]
> Further progress made: I closed out of the Riva Statistics server.

This was the culprit for me. After closing RTSS (and Afterburner since it kept opening RTSS) it works for me now.
(I didn't need to do the antivirus exclusion thing)

Thanks for sharing your solution and thanks to sd805 for the amazing mod

**Comment by SwiftShadow0** [comment]
@Hicks613 If you're still having issues with the motion controls, try enabling SteamVR theatre mode again if you've disabled it

**Comment by Bluscream** [comment]
> I now have fixed arms in the ground. No motion controls. But I can move around. THumbsticks work, all buttons work. I can shoot. I can pick up items, but my avatar arms are in the ground, therefore always shooting up dust. I can even run away from my avatar arms and keep shotting the ground back there at the start point.

How did you fix this? I have the same issue rn

**Comment by Hicks613** [comment]
I have some issues running virtual desktop and then playing this game.  Sometimes control mappings don't bind.
However, airlink fixed this.
Something about how virtual desktop presents the desktop to the hmd, then I use the controllers as a mouse to open steamvr and launch the game confuses the heck out of the bindings.
@Bluscream What's your hmd?

**Comment by Bluscream** [comment]
Quest 2. Got it working with VD, but not consistently. Maybe @ggodin knows more

**Comment by Hicks613** [comment]
0.4.x seems to work.  But my VD just updated last night too.  So maybe thats a thing.
