### ISSUE TITLE
no stick turning - now solved, link in this thread

### ISSUE THREAD

**Issue by kjr81** [sd805/l4d2vr#3]
I need to set to full screen to get any reasonable resolution but that crashes the game, the ones available in windowed mode are to low to be usable. Is there a workaround? 
Nvidia 3090
Also is there any stick turning available? Seems to be physical only.

**Comment by sd805** [comment]
Do you mean the DSR resolutions aren't available in windowed mode? I used DSR to increase the desktop resolution itself which makes them available in windowed mode. 
I plan to add stick turning when I'm back to my PC in a few days.

**Comment by kjr81** [comment]
Yeah so I just start my desktop in 4k and the res is there. Can't wait for the stick turning. Other than that it seems pretty much awesome. No donate button?

**Comment by jsteamjunkie** [comment]
+1 on the stick turning - that would be amazing sd805

**Comment by kjr81** [comment]
I am hoping for it this weekend 🤞

**Comment by jsteamjunkie** [comment]
THANK YOU!!!

**Comment by kjr81** [comment]
I'm not making it though 😂😂 I'm just hoping like you

**Comment by jsteamjunkie** [comment]
lol sorry, I had a heavy night...😂

**Comment by sd805** [comment]
My trip is longer than I was expecting, but I tried to implement stick turning anyway without a headset to test it. No idea if it works: [L4D2VR.zip](https://github.com/sd805/l4d2vr/files/8694953/L4D2VR.zip)

**Comment by kjr81** [comment]
I will try and let you know shortly 👍

**Comment by kjr81** [comment]
Just did a very quick test and nothing seems to be different, the bindings in steam vr show none for east and west. This is on the G2, everything else working fine as before

**Comment by sd805** [comment]
Is there a Turn action available for the thumbstick? This is how the Index's bindings look: [https://i.imgur.com/qg5bNRl.png](https://i.imgur.com/qg5bNRl.png)

**Comment by kjr81** [comment]
I couldn't see one, only move

**Comment by kjr81** [comment]
I will check again shortly, tried to edit the bindings and it broke everything so I have reinstalled the mod

**Comment by kjr81** [comment]
Ok so this was me in my excited rush installing the original mod 🤦 and in doing so then editing my config so I have broke loads of stuff. Thanks, turning speed seems fast not sure how to slow it down a touch?

**Comment by jsteamjunkie** [comment]
I've just tried this on my Index/Knuckles sd805 - thank you for the update

As kjr81 says, it does work and the right thumbstick now controls turning on the sticks L-R axis although the sensitivity is very high. However the Up-Down is still tied to selecting weapons/medkit etc. so it often results in a mix of the two when turning.  Is there a way to move the select gun/medkit from the stick to another key?

Again thanks for the update its really improved moving

**Comment by kjr81** [comment]
I am ok with the up and down for weapon/item selection, didn't seem to cause any issues and I don't think any buttons are left.

**Comment by jsteamjunkie** [comment]
really, have you got knuckles? It makes it incredibly difficult for me as almost any up/down movement in the stick when turning switches weapon to healthpack etc.

**Comment by kjr81** [comment]
I have a G2 so maybe different experience, only changed weapon when I intended to.

**Comment by sd805** [comment]
Here's a new version with a config.txt that should let you change turn speed, enable snap turning, and change IPD. You should be able to edit it while the game is running: [L4D2VR.zip](https://github.com/sd805/l4d2vr/files/8728998/L4D2VR.zip) (also haven't tested this with a headset).
 
@jsteamjunkie If you're using the default bindings, try editing bindings_knuckles.json, ctrl-F for "dpad", and increase [this](https://i.imgur.com/AYgf8yK.png) value to around 60.

**Comment by jsteamjunkie** [comment]
@sd805 thank you so much for this. it is very much appreciated!

**Comment by kjr81** [comment]
Works fine thank you, .3 seemed a good turning speed to me

**Comment by foxhound525** [comment]
How did you guys get stick turning to work? I'm using v0.3 and there's no turning by default

**Comment by foxhound525** [comment]
... so you're gonna mark it as resolved but not tell anyone how to fix it... dude
