### ISSUE TITLE
Crashes when loading into a game

### ISSUE THREAD

**Issue by foxhound525** [sd805/l4d2vr#30]
So I dropped the contents of the v0.3 .rar into the install directory for L4D2, add the launch commands, run steamvr, run the game. I go through the menu for graphics, start a new local server game etc, then press start. It loads, and then the headset blackens like its going to do something, there's audio or a few seconds in the hmd, game crashes. Every time

Index HMD, Vive controllers
1060 6GB
3800X
16GB RAM
Win10

**Comment by mamefan** [comment]
Put it on low memory pool.

**Comment by foxhound525** [comment]
> 

Thank you, I can now get into a game. New problem now, I have no models for my hands/weapons, so I can't shoot anything. I hear the gunshots but nothing gets hit

**Comment by mamefan** [comment]
Check use desktop game theatre when steamvr is active in L4D2 properties. Opposite of every other vr mod. Makes hands/weapons appear.

**Comment by foxhound525** [comment]
Ok thank you, that fixed it.

(Hopefully) Last question; how do you use smooth turning? I've tried all the vive community binds and none seem to allow turning. I looked in that config and it's currently set like this (unaltered)

TurnSpeed=0.3
SnapTurning=false
SnapTurnAngle=45.0
VRScale=43.2
IPDScale=1.0

**Comment by mamefan** [comment]
No idea. I physically turn.

**Comment by foxhound525** [comment]
Ok, thank you anyway. I'l mark the original issue as closed.
