### ISSUE TITLE
Smooth turning doesn't work

### ISSUE THREAD

**Issue by foxhound525** [sd805/l4d2vr#33]
So I've managed to get the game to not crash on load (set mem pool to low) actually display my arms (run in theatre mode) and now the last hurdle seems to be smooth turning.

I downloaded v0.3 which is supposed to have it, but it doesn't work. Pressing left and right on the right vive controller doesn't turn, and using other community bindings doesn't help either.

I checked the config file and it looks like it should be working, it just doesn't actually work so not sure what to do.

GTX 1060 6GB
3800X
16GB RAM
Valve index HMD + Vive wands

**Comment by sd805** [comment]
In the SteamVR bindings menu, click the plus sign on trackpad and select "Use as trackpad." Then set Position to turn. Should look like [this](https://i.imgur.com/dcmVEvh.png).

**Comment by foxhound525** [comment]
Thank you, I will try this on the weekend.

**Comment by foxhound525** [comment]
> In the SteamVR bindings menu, click the plus sign on trackpad and select "Use as trackpad." Then set Position to turn. Should look like [this](https://i.imgur.com/dcmVEvh.png).

That's done it, thank you.
