### ISSUE TITLE
Can't get it to work?

### ISSUE THREAD

**Issue by SpiraIt** [sd805/l4d2vr#34]
I have tried disable game theater mode i tried putting a exclusion i tried a/f6 but the game crashes as after the campaign thing loads i don't know what to do :(

**Comment by quidnun** [comment]
same. probably not you. crashes on campaign load (hear some sounds and then it just drops to desktop)

I do have the current SteamVR beta (someone mentioned that might be an issue - could try rolling back)

**Comment by sd805** [comment]
Does the new version work?

**Comment by SpiraIt** [comment]
> Does the new version work?

YES! of course its lagging cause of the dxvk thing but thats it holy shit thanks :D
