### ISSUE TITLE
the screen is wide and weird

### ISSUE THREAD

**Issue by imalilstupid** [sd805/l4d2vr#36]
idk if its something with my settings but whenever i load the screen is so wide and its unplayable. like i can barely see what im doing. anyone know a fix?

**Comment by sd805** [comment]
In v0.4.2? Is the menu messed up, the VR view, or both?

**Comment by Hicks613** [comment]
This is normal.  Its wide and weird on the desktop.  F6 transfers to hmd and it looks great.

**Comment by imalilstupid** [comment]
> In v0.4.2? Is the menu messed up, the VR view, or both?

everything in the vr is all wide and messed up, on the pc its just frozen

**Comment by imalilstupid** [comment]
fixed it. we all good
