### ISSUE TITLE
Gun/Controller align issue

### ISSUE THREAD

**Issue by UndeadSlayer836** [sd805/l4d2vr#38]
Not sure if this is a problem for everyone or just me but using quest 2 link cable the location of the firearms in game are aligned far more to the right than the location of my quest 2 controller in the real world

**Comment by BandyScroll65923** [comment]
it could be a problem with your fov if you changed it with the command "fov_desired" if you didn't then it is definitely something either wrong with the controllers or maybe the quest 2

**Comment by UndeadSlayer836** [comment]
uh oh, hope my quest is ok wish me luck! gonna test a bit with other games, would still be nice to have in game positioning options just to help the offset or make the experience feel more custom and nice

**Comment by BandyScroll65923** [comment]
has this issue happened on other games or just left 4 dead?

**Comment by UndeadSlayer836** [comment]
was finally able to check and my controllers are both tracking accurately to irl position, saying the gun shows up far to the right might have been inaccurate it's not crazy far over but it is off and just a little annoying. someone mentioned fov to me and while I do not remember changing my fov I am playing on pc so I might have crunk it up a bit and forgot lol. what is a good value to set fov at for the vr mod? I don't mind changing it over to anything as I plan on playing from vr for now on anyone.

**Comment by UndeadSlayer836** [comment]
nvm, the dev literally replied to the other issue thread saying it's just the offset the gun are using rn so I'll just wait for an update.
