### ISSUE TITLE
Unable to launch into VR

### ISSUE THREAD

**Issue by Richleth** [sd805/l4d2vr#5]
Debug log gives dhcp_proxy_script_adapter_fetcher_win.cc(265)] Error fetching PAC URL from DHCP: 2 error

I have no add-ons and have validated game files. Running on high memory page pool and low settings boots into the campaign but I am unable to launch into VR. Same for the recommended settings on the imgur link. SteamVR is reporting the game is running but just shows a default environment. 

If I run the recommended settings but with high memory page pool the game will just crash instead.

Valve Index + Knuckles | RTX 2070 SUPER | AMD Ryzen 9 3950x 16-Core Processor | 64GB Ram | Main SteamVR Branch

**Comment by jsteamjunkie** [comment]
Same issue for me too. Game loads okay on Desktop, Sound in Valve Index but no screen, just the standard Steam default environment (F6/Controller button doesnt have any impact). I followed the readme with settings etc. 100% multiple times but just not working.

If I open a Steam/Desktop window I can see the 2D game, but not 3D/VR

Valve Index + Knuckles / RTX 1080 / Alienware Aurora R7 / 16GB Ram / Steam

**Comment by sd805** [comment]
When you load into a campaign and activate VR mode does the game change in any way? When the mod works correctly the game window should look frozen as it starts rendering to the headset.

**Comment by jsteamjunkie** [comment]
No nothing seems to happen at all - seems when I press either the F6 key (or A on Controller) nothing happens...

Will try again now to see if Shift F6 or similar works...

**Comment by jsteamjunkie** [comment]
A clean install sorted the problem for me. GREAT GAME - really enjoying it VR - thanks sd805 this is awesome!!

If anyone knows a way I can rotate using the knuckels right stick that would be perfect....

**Comment by Richleth** [comment]
Same as jsteamjunkie that nothing seems to happen at all and will also try a clean reinstall

**Comment by Richleth** [comment]
No, a fresh install did not fix the problem for me. I can get Virtual Fortress 2 to work just fine but this just gives me that error and prevents me from booting into VR. I always am launching SteamVR before L4D2 but I know my SteamVR does launch itself on launching L4D2 first.

**Comment by Richleth** [comment]
I think Ill just wait till the next public release and try again then. I'm pretty sure I have it installed right but a video for installation would probably help. Can't wait to see how far this project will go (and if I can ever play it on my machine).

**Comment by rorincloud** [comment]
What got it working for me was changing the Shader detail option to medium or low.

**Comment by Richleth** [comment]
> What got it working for me was changing the Shader detail option to medium or low.

Already tried this

**Comment by CrackedDish** [comment]
Having an issue to where the game boots up okay on Desktop using Steam, but the Valve Index stays on this Steam VR 'Next Up' screen as the game is loading on the Desktop. I have sound in the headset the entire time. (I start Steam VR before booting up the game)
I try to start a single player game (using the mouse and keyboard on my PC monitor, as the Index controllers do nothing).  After hitting "Start" with the mouse, the game crashes within 5-10 seconds and kicks me out to the Main Steam VR screen.

I have tried a fresh re-install of the game, and followed the VR instructions religiously, but the game crashed as described above.
I also tried starting up the game on Desktop first, before installing the VR mod, but the game crashed in the same manner.

Valve Index (90Hz refresh + Motion Smoothing On). i7-8700, 16GB RAM, GTX1070Ti

**Comment by Richleth** [comment]
Used latest version in the "no stick turning - now solved, link in this thread" thread and still am unable to boot into VR. VR mode just refuses to activate

**Comment by laurensbainton** [comment]
I too am unable to go into vr mode using F6 or A on the controller

**Comment by Richleth** [comment]
Excluding from windows defender and closing out of rivatuner statistics server fixed my issue
