### ISSUE TITLE
Screen tearing when firing weapons

### ISSUE THREAD

**Issue by Ubernoodles** [sd805/l4d2vr#77]
I love the mod & it seems to work wonderfully with my Quest 2, Intel i7 10, RTX 2070. However, the only issue spoiling immersion is this annoying screen tearing when firing weapons. It does not happen with simple movement or melee weapons, only with the muzzle flash from firing guns.
Is anyone else experiencing this issue? It doesn't seem to be present when watching other peoples YouTube playthroughs
Thanks for bringing this mod to the world.

**Comment by Ubernoodles** [comment]
Solution found here:
https://github.com/sd805/l4d2vr/issues/76
Left4Dead2 does not like ASR. Turning this setting from Auto to Off has improved some of my other games too.
For other Quest users having the same issue, you can turn off ASR without the debug tool by pressing Ctrl and Numpad 1 together. Do this at anytime whilst headset linked with cable or airlink. You will have to do this every time you connect to PC as ASR defaults to Auto at every reset.

**Comment by Leniptic** [comment]
You can also use the Oculus Debug Tool to disable it, if the numpad combination doesn't work for you/Oculus Tray Tool doesn't. Makes me feel better it wasn't just me having this issue.
